language: ruby
rvm:
  - 2.5.0

sudo: false

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
#  - sudo apt-get install libcurl3-dev

before_script:
 - chmod +x ./script/cibuild

script: ./script/cibuild

cache: bundler

notifications:
email: false